name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive artifact
        run: |
          tar --dereference --hard-dereference \
              --directory "dist" \
              -cvf "$RUNNER_TEMP/artifact.tar" \
              --exclude=.git \
              --exclude=.github \
              .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: $RUNNER_TEMP/artifact.tar
